# Generated by Django 5.1.6 on 2025-03-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newjobpost_date_newjobpost_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewJobPost',
            new_name='JobPost',
        ),
    ]
