# Generated by Django 5.1.6 on 2025-03-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_uploadfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='image',
            new_name='file',
        ),
    ]
